language: ruby
rvm:
- 2.3.1
script: rspec
gemfile:
- Gemfile
notifications:
  email: false
  slack:
    secure: t28Z/6a6jQWUAwm++SR8fa1uH/7ltCiBb70kauP2iAXwHlZqCaDFdhQpnWzv1yFDs09wJfixWToYNBdtSOmpEQe9fN+AFm68ID0JURxugGHQ/ZHRmgMznXVY9xeV1TGiFb4e7wvdpTyTKOy9x1tQbWT6nVkmMK4QPEsr8gdUVOHnHCRUhb6oCe0GsvQ9r7C3MCucy5mudhDsB5dGET5M2m02HPcV/o0y5tJoJnr8zVIxnMAvjQxGqZUDcqybelQZ8QWm72Cov+XZ8wOdITbbbirrXQdALkgznzBzB2fgPHnC3haL1zd961I0x7ONXvPGOH0rUNz3AjWYMwM5Y47NQlfSZmQkDnUiFZ4A9pQQSOb3pUUXEyZmgMHPuE7SHtDvZBrhVNbg6MGpS/1+02eTY5MO5t40oxN+rHZjcM96yjvtzkBFDyBbRsByEVmwDvR+72a4UmIBiPsGL2F4jHW65okBUuguok2qUuzwWb913zTqaHPvTxkZeiCnQqLzM5drn6Tbe0HElGYIihKs1VUv2xz9fzzSkycvgJtJr75WyFWeElzrBX+HXCNANtsf8V/a8a6g6kB72z/yLWkjhS6QulExXiDvhJd+iFIDMVmTQJ8kEmCg06PWWpLpx49yfn1RCjgum0Y2WaCli4plT3T8G/WC1t+QAqCh0J1UMe8cIRA=
